# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.author }}, {{ site.github_username }}, etc.

# theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes@4.24.0

# Site title, url, and description
title: "Development Blog"
# subtitle: "ğŸ‘¨â€ğŸ’»"
description: "ë°°ìš°ê³  ì„±ì¥í•˜ëŠ” ê³¼ì •ì„ ê¸°ë¡í•©ë‹ˆë‹¤."
url: ""

# Skin
minimal_mistakes_skin: "" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Search
search: true

# Minimal Mistakes Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author settings
author:
  name: "A Developer"
  avatar: "/assets/images/my_profile.png" # ì—¬ê¸°ì— ì‹¤ì œ í”„ë¡œí•„ ì‚¬ì§„ ê²½ë¡œë¥¼ ì§€ì •í•˜ì„¸ìš”.
  bio: "Writing code, solving problems, and learning along the way."
  location: "Seoul, South Korea"
  # links:
  #   - label: "GitHub"
  #     icon: "fab fa-fw fa-github"
  #     url: "https://github.com/garam-dev"
  #   - label: "LinkedIn" # ì˜ˆì‹œ: LinkedIn ì¶”ê°€
  #     icon: "fab fa-fw fa-linkedin"
  #     url: "https://www.linkedin.com/in/your-linkedin-profile/" # ë³¸ì¸ì˜ LinkedIn í”„ë¡œí•„ URLë¡œ ë³€ê²½í•˜ì„¸ìš”.

# Footer settings
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/garam-dev"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "assets/js"
      type: pages
    values:
      layout: single
      author_profile: true

# Supabase Comments settings
supabase:
  url: "https://bnvrbmsmjqbguwyixsum.supabase.co"
  key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJudnJibXNtanFiZ3V3eWl4c3VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMzI2NTYsImV4cCI6MjA2NzcwODY1Nn0.jCMqRociGCQwKUZ09DYWwzhelt4fVGAItj2jcXHiIJY"

# Repository
repository: garam-dev/garam-dev.github.io
